version: '3.2'

services:
    db:
      # TODO: look for pre-build images postgis/postgis:9.6-2.5
      image: thedeep/deep-postgres:latest
      build:
        context: ./server/postgres/
        cache_from:
          - thedeep/deep-postgres:latest
      environment:
        POSTGRES_PASSWORD: postgres
      volumes:
        - postgres-data:/var/lib/postgresql/data

    redis:
      image: redis:5
      volumes:
        - redis-data:/data

    server:
      image: thedeep/deep-server:latest
      build:
        context: ./server/
        cache_from:
          - thedeep/deep-server:latest
      tty: true
      env_file:
        - .env
      command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
      volumes:
        - ./server/:/code
        - media:/media
      ports:
        - '8000:8000'
      depends_on:
        - db
        - redis

    client:
      image: thedeep/deep-client:latest
      build:
        context: ./client/
        cache_from:
          - thedeep/deep-client:latest
      tty: true
      env_file:
        - .env
      command: bash -c '/code/scripts/run_develop.sh'
      volumes:
        - ./client/:/code
      ports:
        - '3000:3000'

volumes:
  media:
  postgres-data:
  redis-data:
